"use client";

import { useEffect, useState } from "react";

import { useRouter } from "next/navigation";

type Meeting = {
  meeting_id: string;
  meeting_title: string;
  timestamp: string;
};

export default function PreviousMeetings() {
    

  const router = useRouter();

  const [meetings, setMeetings] =
    useState<Meeting[]>([]);

  const [loading, setLoading] =
    useState(true);

  useEffect(() => {

    async function fetchMeetings() {

      try {

        const response = await fetch(
          "http://127.0.0.1:8000/meetings"
        );

        const data =
          await response.json();

        setMeetings(data);

      } catch (error) {

        console.error(error);

      } finally {

        setLoading(false);
      }
    }

    fetchMeetings();

  }, []);

  function formatTimestamp(
    timestamp: string
  ) {

    return new Date(
      timestamp
    ).toLocaleString(
      "en-DE",
      {
        day: "numeric",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      }
    );
  }

  return (

    <section
      id="meetings"
      className="
        w-full
        max-w-7xl
        mx-auto
        px-6
        py-24
      "
    >

      {/* Heading */}

      <div
        className="
          mb-12
        "
      >

        <h2
          className="
            text-4xl
            md:text-5xl
            font-bold
            tracking-tight
            text-white
          "
        >

          Previous Meetings

        </h2>

        <p
          className="
            text-gray-500
            mt-4
            text-lg
            max-w-2xl
          "
        >

          Browse previously analyzed
          meetings and revisit operational
          insights generated by Rus.

        </p>

      </div>

      {/* Loading */}

      {loading && (

        <div
          className="
            text-gray-500
            text-sm
          "
        >

          Loading meetings...

        </div>
      )}

      {/* Empty */}

      {!loading &&
        meetings.length === 0 && (

        <div
          className="
            border
            border-white/10
            rounded-[28px]
            bg-[#141821]
            p-10
            text-center
            text-gray-500
          "
        >

          No meetings analyzed yet.

        </div>
      )}

      {/* Cards */}

      <div
        className="
          grid
          md:grid-cols-2
          xl:grid-cols-3
          gap-6
        "
      >

        {meetings.map(
          (meeting) => (

            <button

              key={
                meeting.meeting_id
              }

              onClick={() =>
                router.push(
                  `/meeting/${meeting.meeting_id}`
                )
              }

              className="
                group
                text-left
                rounded-[30px]
                border
                border-white/8
                bg-[#141821]
                hover:bg-[#181d28]
                transition-all
                duration-300
                p-7
                min-h-[180px]
                flex
                flex-col
                justify-between
              "
            >

              {/* Top */}

              <div>

                <div
                  className="
                    text-white
                    text-2xl
                    font-semibold
                    leading-snug
                    tracking-tight
                    group-hover:text-gray-100
                    transition-colors
                    duration-200
                    line-clamp-3
                  "
                >

                  {meeting.meeting_title}

                </div>

              </div>

              {/* Bottom */}

              <div
                className="
                  mt-8
                  pt-5
                  border-t
                  border-white/5
                "
              >

                <div
                  className="
                    text-sm
                    text-gray-500
                  "
                >

                  {formatTimestamp(
                    meeting.timestamp
                  )}

                </div>

              </div>

            </button>
          )
        )}

      </div>

    </section>
  );
}